# -*- coding: utf-8 -*-
"""DS397_String_Matching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5KUe0ZW61z1G11Y8L9oqoOf-w3D9xQK
"""

def string_match(text, pattern):
  # assigns the length of the pattern to variable pat_len
  pat_len = len(pattern)
  # for loop that iterates through the total length of the text
  for i in range(len(text)):
    # checks to see if each element of the text is equal to the first element of the pattern
    if text[i] == pattern[0]:
      # checks to see if the sliced substring of the text from index i to (i + length_of_pattern) is the same as the pattern
      # if it is then we return the start index of the text where it matches the pattern 
      if text[i:pat_len+i] == pattern:
        return(i)